#When using another repository to run this repository it will...
name: "Podcast Generator"
author: "Dan Dahl"
description: "Generates feed for a podcast from a YAML file"
runs: 
  using: "docker"
  image: "Dockerfile" #Use Dockerfile to set up server, which uses entrypoint to set up git, run app, and push to server
branding: 
  icon: "git-branch" #For the Marketplace ==> from a library called Feather-icons
  color: "red"
inputs: #We're relying on some variables being available to us
  email: 
    description: The committer's email address
    required: True
    default: ${{ github.actor }}@localhost
  name: 
    description: The committer's name
    required: True
    default: ${{ github.actor }}